# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: masl

builds:
  - id: default-build
    main: ./cmd/masl/masl.go
    goos:
      - linux
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

  - id: build-osx
    main: ./cmd/masl/masl.go
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch

signs:
  - signature: "${artifact}.dmg"
    ids:
      - build-osx # filter the macos only build id
    cmd: gon
    args:
      - .gon.json
    artifacts: all

archives:
  - id: binaries
    builds:
      - build-osx
    format: binary
    replacements:
      darwin: Darwin

  - id: archives
    builds:
      - default-build
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

release:
  ids:
    - archives
  extra_files:
    - glob: ./dist/masl.dmg

brews:
  - description: "Assume an AWS Role using Onelogin."
    tap:
      owner: glnds
      name: masl
