# This file was generated by GoReleaser. DO NOT EDIT.
class Masl < Formula
  desc "Assume an AWS Role using Onelogin."
  homepage ""
  version "2.0.5"
  bottle :unneeded

  if OS.mac?
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/glnds/masl/releases/download/v2.0.5/masl_2.0.5_Linux_x86_64.tar.gz"
      sha256 "6bbc0c15d564d20344133d414448803476df33757c3cf8a48921ea26b57b858a"
    end
  end

  def install
    bin.install "masl"
  end
end
