# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Masl < Formula
  desc "Assume an AWS Role using Onelogin."
  homepage ""
  version "2.0.6"
  bottle :unneeded
  depends_on :linux

  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/glnds/masl/releases/download/v2.0.6/masl_2.0.6_Linux_x86_64.tar.gz"
    sha256 "986846f2581328253f92be1bf35a49682bb7c49621497a8640c15ef53b63d145"
  end

  def install
    bin.install "masl"
  end
end
